Fix Docker commands in scripts
hummingbird-me/hummingbird pull request #814
Opened 2021-06-01 15:00 UTC by lunaisnotaboy

This fixes a problem I had with setting a development environment.

**Changes proposed in this pull request:**
- The setup scripts were calling `docker compose` instead of `docker-compose`.
- [`docker-compose.yml`](https://github.com/hummingbird-me/kitsu-tools/blob/the-future/docker-compose.yml) also referred to a nonexistent Dockerfile in the server repository, so I corrected that as well.

cc @hummingbird-me/owners

2021-06-21 06:15 UTC, NuckChorris requested changes
Thanks for the PR, sorry I didn't get to it earlier! I actually changed everything to `docker compose` because the Docker CLI told me it was now included, but apparently [that's a lot less stable than they implied](https://github.com/docker/compose-cli/issues/1149) so :+1: on going back to `docker-compose`

2021-06-21 06:15 UTC, NuckChorris commented on docker-compose.yml
> +      dockerfile: Dockerfile
Can you revert this one line? This was intentional, I just forgot to push the Dockerfile.local and did that now 😅

2021-10-22 11:30 UTC, lunaisnotaboy commented on docker-compose.yml
> +      dockerfile: Dockerfile
Oh yeah, sorry!!

2021-10-22 11:36 UTC, lunaisnotaboy commented on docker-compose.yml
> +      dockerfile: Dockerfile
Fixed in 0baf183.

2021-10-26 12:02 UTC, lunaisnotaboy commented
@NuckChorris Sorry it took so long to fix the `docker-compose.yml` file, but it's now ready!

2021-11-30 16:46 UTC, lunaisnotaboy commented
I accidentally deleted the repository while cleaning up my profile, so this pull request will be recreated.

Sorry!

/cc @NuckChorris

2021-11-30 16:46 UTC, closed without merging